# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- master

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: BuildProject
    displayName: Build Project

    pool:
      vmImage: ubuntu-latest
    steps:

    - task: SonarCloudPrepare@1
      displayName: 'Prepararing Sonar'
      inputs:
        SonarCloud: 'sonar-azuredevops'
        organization: 'josedanielbaena'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'lazyloadfront'
        cliProjectName: 'lazyloadfront'
        cliSources: 'src'
  
    - task: NodeTool@0
      displayName: 'Installing Node.js'
      inputs:
        versionSpec: '14.x'

    - script: |
        npm install -g @angular/cli
        npm install
        npm run build
      displayName: 'Installing npm and building'

    - task: SonarCloudAnalyze@1
      displayName: 'Running code analysis'

    - task: SonarCloudPublish@1
      displayName: 'Publishing code analysis result'
      inputs:
        pollingTimeoutSec: '300'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'dist'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/artifact.zip'
        replaceExistingArchive: true
      
    - task: PublishBuildArtifacts@1
      displayName: Publishing Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'artifact'
        publishLocation: 'Container'

    - task: Docker@2
      displayName: 'Uploading image to DockerHub'
      inputs:
        containerRegistry: 'dockerhubconnection'
        repository: 'bazul98/lazy-load-front'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        buildContext: '.'
        tags: |
          $(Build.BuildId)
          latest
        addPipelineData: false
        addBaseImageData: false

